# -*- coding: utf-8 -*-
"""MonitorizacionHRV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14najmM9AenrtVdPAOIq2pX93NqBPa4re

#Monitorización HRV

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/14najmM9AenrtVdPAOIq2pX93NqBPa4re?usp=sharing)

El script automatiza el **análisis de la frecuencia cardiaca registrada durante cada sesión**. Para ello, relaciona las hojas del archivo de frecuencia cardiaca con la información incluida en el **archivo de valoración**, donde se recogen la *fecha de cada sesión*, los *tiempos de inicio y final* de las partes de fuerza, funcional y resistencia, los *valores de percepción subjetiva del esfuerzo* —RPE— y las *frecuencias cardiacas máximas utilizadas como referencia*.

Para cada parte de la sesión, el programa selecciona únicamente las muestras de frecuencia cardiaca comprendidas entre el tiempo inicial y el tiempo final indicados. A continuación, clasifica cada muestra en una de seis zonas de intensidad, calculadas como porcentajes de la frecuencia cardiaca máxima de referencia:

**Z1: 60–69.99%.**

**Z2: 70–79.99%.**

**Z3: 80–89.99%.**

**Z4: 90–99.99%.**

**Z5: 100–109.99%.**

**Z6: >=110%.**

El **análisis** se realiza de forma independiente para los **valores HRMAX50 y HRMAX75** incluidos en la hoja de valoración. De este modo, se obtiene una distribución del tiempo en zonas para cada una de las dos frecuencias cardiacas máximas de referencia.

Los **límites de cada zona** se calculan multiplicando la frecuencia cardiaca máxima correspondiente por el porcentaje de la zona. Los resultados se redondean al latido por minuto más próximo mediante redondeo convencional. Por ejemplo, para una frecuencia cardiaca máxima de 174 latidos·min⁻¹, el límite superior de Z1 se calcula como 174 × 0,70 = 121,8, que se redondea a 122 latidos·min⁻¹.

El **tiempo acumulado en cada zona** se obtiene a partir del número de muestras clasificadas y del intervalo de muestreo del registro. Los resultados se expresan tanto en segundos como en minutos. Cuando los datos están registrados con una frecuencia de una muestra por segundo, cada muestra equivale a un segundo de permanencia en la zona correspondiente.

El programa permite decidir si los valores inferiores al 60% de la frecuencia cardiaca máxima deben incluirse dentro de Z1 o contabilizarse por separado. Desde un punto de vista metodológico, la opción más estricta consiste en excluirlos de Z1, ya que esta zona se define específicamente entre el 60% y el 70%.

Las sesiones se emparejan preferentemente mediante la fecha registrada en ambos archivos. Además, el script comprueba si los intervalos definidos para cada parte de la sesión se encuentran dentro del periodo disponible de frecuencia cardiaca. *Cuando un intervalo supera la duración del registro, puede recortarse hasta el último dato disponible, dejando constancia de esta modificación en una hoja de control.*

Finalmente, se **genera un archivo Excel con una hoja independiente para cada sesión**. En cada hoja se presentan los tiempos en las seis zonas para las partes de fuerza, funcional y resistencia, junto con sus correspondientes valores de RPE. También se crea una hoja de control que permite revisar el emparejamiento de las sesiones, los intervalos analizados, el número de muestras disponibles y cualquier incidencia detectada durante el procesamiento.
"""

# @title
!pip -q install openpyxl ipywidgets

import re
import unicodedata
from decimal import Decimal, ROUND_HALF_UP
from datetime import datetime, date, time

import numpy as np
import pandas as pd
import ipywidgets as widgets

from IPython.display import display, clear_output
from google.colab import files
from openpyxl import load_workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Alignment,
    Border,
    Side,
)
from openpyxl.utils import get_column_letter


# ================================================================
# FUNCIONES AUXILIARES
# ================================================================

def normalizar(valor):
    """
    Normaliza encabezados eliminando tildes, espacios y símbolos.
    """
    if valor is None:
        return ""

    valor = unicodedata.normalize(
        "NFKD",
        str(valor),
    )

    valor = "".join(
        caracter
        for caracter in valor
        if not unicodedata.combining(caracter)
    )

    return re.sub(
        r"[^A-Z0-9]",
        "",
        valor.upper(),
    )


def esta_vacio(valor):
    try:
        return valor is None or pd.isna(valor)
    except Exception:
        return valor is None


def convertir_fecha(valor):
    """
    Convierte fechas de Excel, pandas o texto a datetime.date.
    """
    if esta_vacio(valor):
        return None

    if isinstance(valor, pd.Timestamp):
        return valor.date()

    if isinstance(valor, datetime):
        return valor.date()

    if isinstance(valor, date):
        return valor

    if isinstance(
        valor,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    ):
        return (
            pd.Timestamp("1899-12-30")
            + pd.to_timedelta(
                float(valor),
                unit="D",
            )
        ).date()

    valor = pd.to_datetime(
        valor,
        dayfirst=True,
        errors="coerce",
    )

    if pd.isna(valor):
        return None

    return valor.date()


def convertir_a_segundos(valor):
    """
    Convierte una hora o duración de Excel a segundos.
    """
    if esta_vacio(valor):
        return None

    if isinstance(valor, pd.Timedelta):
        return float(valor.total_seconds())

    if isinstance(valor, datetime):
        return (
            valor.hour * 3600
            + valor.minute * 60
            + valor.second
            + valor.microsecond / 1e6
        )

    if isinstance(valor, time):
        return (
            valor.hour * 3600
            + valor.minute * 60
            + valor.second
            + valor.microsecond / 1e6
        )

    if isinstance(
        valor,
        (
            int,
            float,
            np.integer,
            np.floating,
        ),
    ):
        valor = float(valor)

        # Excel almacena las horas como fracciones de un día.
        if abs(valor) < 2:
            return valor * 86400

        return valor

    texto = str(valor).strip().replace(",", ".")

    if ":" in texto:

        partes = [
            float(elemento)
            for elemento in texto.split(":")
        ]

        if len(partes) == 3:
            return (
                partes[0] * 3600
                + partes[1] * 60
                + partes[2]
            )

        if len(partes) == 2:
            return (
                partes[0] * 60
                + partes[1]
            )

    valor = float(texto)

    if abs(valor) < 2:
        return valor * 86400

    return valor


def redondear_umbral(valor):
    """
    Aplica redondeo convencional:
    148.5 se transforma en 149.
    """
    return int(
        Decimal(
            str(float(valor))
        ).quantize(
            Decimal("1"),
            rounding=ROUND_HALF_UP,
        )
    )


def segundos_a_hms(valor):
    """
    Convierte segundos a HH:MM:SS.
    """
    if valor is None or pd.isna(valor):
        return ""

    valor = max(
        0,
        int(round(float(valor))),
    )

    horas, resto = divmod(
        valor,
        3600,
    )

    minutos, segundos = divmod(
        resto,
        60,
    )

    return (
        f"{horas:02d}:"
        f"{minutos:02d}:"
        f"{segundos:02d}"
    )


def obtener_valor(
    fila,
    columnas,
    *nombres,
):
    """
    Busca una variable en la fila RPE aceptando varias formas
    posibles de escribir su encabezado.
    """
    for nombre in nombres:

        columna_original = columnas.get(
            normalizar(nombre)
        )

        if columna_original is not None:

            valor = fila[
                columna_original
            ]

            if not esta_vacio(valor):
                return valor

    return None


def nombre_hoja_seguro(
    nombre,
    existentes,
):
    """
    Genera un nombre de hoja válido y no repetido.
    """
    nombre = re.sub(
        r"[\[\]\*\?/\\:]",
        "_",
        str(nombre),
    )

    nombre = nombre[:31] or "Sesion"
    nombre_base = nombre

    contador = 2

    while nombre in existentes:

        sufijo = f"_{contador}"

        nombre = (
            nombre_base[
                :31 - len(sufijo)
            ]
            + sufijo
        )

        contador += 1

    return nombre


# ================================================================
# LECTURA DE LAS HOJAS HRV
# ================================================================

def leer_hoja_hrv(
    ruta,
    hoja,
):
    """
    Lee una hoja del Excel de HRV.

    Devuelve:
    - fecha de la sesión;
    - tiempo en segundos;
    - frecuencia cardiaca;
    - periodo de muestreo;
    - inicio y final del registro.
    """

    datos_brutos = pd.read_excel(
        ruta,
        sheet_name=hoja,
        header=None,
        dtype=object,
    )

    if datos_brutos.empty:
        raise ValueError(
            f"La hoja {hoja} está vacía."
        )

    # ------------------------------------------------------------
    # Extraer metadatos de las dos primeras filas
    # ------------------------------------------------------------

    metadatos = {}

    if len(datos_brutos) >= 2:

        for encabezado, valor in zip(
            datos_brutos.iloc[0].tolist(),
            datos_brutos.iloc[1].tolist(),
        ):

            clave = normalizar(encabezado)

            if clave:
                metadatos[clave] = valor

    fecha = convertir_fecha(
        metadatos.get(
            "DATE",
            metadatos.get("FECHA"),
        )
    )

    # ------------------------------------------------------------
    # Localizar la fila que contiene Time y HR (bpm)
    # ------------------------------------------------------------

    fila_encabezado = None
    columna_tiempo = None
    columna_hr = None

    encabezados_tiempo = {
        "TIME",
        "TIEMPO",
        "ELAPSEDTIME",
        "DURATION",
    }

    encabezados_hr = {
        "HR",
        "HRBPM",
        "HEARTRATE",
        "HEARTRATEBPM",
        "FC",
        "FCBPM",
    }

    for numero_fila in range(
        min(20, len(datos_brutos))
    ):

        fila_normalizada = [
            normalizar(valor)
            for valor
            in datos_brutos.iloc[
                numero_fila
            ].tolist()
        ]

        columnas_tiempo = [
            posicion
            for posicion, valor
            in enumerate(fila_normalizada)
            if valor in encabezados_tiempo
        ]

        columnas_hr = [
            posicion
            for posicion, valor
            in enumerate(fila_normalizada)
            if valor in encabezados_hr
        ]

        if columnas_tiempo and columnas_hr:

            fila_encabezado = numero_fila
            columna_tiempo = columnas_tiempo[0]
            columna_hr = columnas_hr[0]

            break

    if fila_encabezado is None:

        raise ValueError(
            f"No se localizaron las columnas "
            f"Time y HR en la hoja {hoja}."
        )

    # ------------------------------------------------------------
    # Extraer únicamente tiempo y frecuencia cardiaca
    # ------------------------------------------------------------

    datos = datos_brutos.iloc[
        fila_encabezado + 1:,
        [
            columna_tiempo,
            columna_hr,
        ],
    ].copy()

    datos.columns = [
        "tiempo_original",
        "hr",
    ]

    # La columna Time contiene datetime.time, por lo que debe
    # convertirse elemento a elemento mediante convertir_a_segundos().
    datos["tiempo_s"] = datos[
        "tiempo_original"
    ].apply(
        convertir_a_segundos
    )

    datos["hr"] = pd.to_numeric(
        datos["hr"],
        errors="coerce",
    )

    datos = datos[
        [
            "tiempo_s",
            "hr",
        ]
    ].dropna()

    datos = (
        datos
        .sort_values("tiempo_s")
        .drop_duplicates(
            subset="tiempo_s",
            keep="first",
        )
        .reset_index(drop=True)
    )

    if datos.empty:

        raise ValueError(
            f"La hoja {hoja} no contiene "
            f"datos válidos de FC después "
            f"de convertir la columna Time."
        )

    datos["tiempo_s"] = (
        datos["tiempo_s"]
        .astype(float)
        .round(6)
    )

    # ------------------------------------------------------------
    # Calcular el periodo de muestreo
    # ------------------------------------------------------------

    diferencias = (
        datos["tiempo_s"]
        .diff()
    )

    diferencias = diferencias[
        diferencias > 0
    ]

    if len(diferencias):

        periodo_muestreo = float(
            diferencias.median()
        )

    else:

        periodo_muestreo = 1.0

    if (
        abs(
            periodo_muestreo
            - round(periodo_muestreo)
        )
        < 1e-6
    ):

        periodo_muestreo = float(
            round(periodo_muestreo)
        )

    return {
        "hoja": hoja,
        "fecha": fecha,

        "datos": datos[
            [
                "tiempo_s",
                "hr",
            ]
        ],

        "periodo": periodo_muestreo,

        "inicio": float(
            datos["tiempo_s"].min()
        ),

        "fin": float(
            datos["tiempo_s"].max()
        ),

        "n_muestras": int(
            len(datos)
        ),
    }

# ================================================================
# LECTURA DE VALORACIÓN RPE
# ================================================================

def leer_valoracion_rpe(
    ruta,
    hoja_rpe,
    sujeto,
):
    """
    Extrae HRMAX50, HRMAX75, RPE e intervalos de cada sesión.
    """
    datos_rpe = pd.read_excel(
        ruta,
        sheet_name=hoja_rpe,
        dtype=object,
    )

    columnas = {
        normalizar(columna): columna
        for columna
        in datos_rpe.columns
    }

    columna_sujeto = columnas.get(
        "SUJETO"
    )

    if columna_sujeto is None:
        raise ValueError(
            "No existe la columna SUJETO "
            "en la hoja RPE."
        )

    seleccion = datos_rpe[
        datos_rpe[columna_sujeto]
        .astype(str)
        .str.strip()
        .str.upper()
        == sujeto.strip().upper()
    ]

    if seleccion.empty:

        sujetos_disponibles = sorted(
            datos_rpe[columna_sujeto]
            .dropna()
            .astype(str)
            .str.strip()
            .unique()
            .tolist()
        )

        raise ValueError(
            f"No se encontró el sujeto {sujeto}. "
            f"Sujetos disponibles: "
            f"{sujetos_disponibles}"
        )

    fila = seleccion.iloc[0]

    hrmax50 = pd.to_numeric(
        obtener_valor(
            fila,
            columnas,
            "HRMAX50",
        ),
        errors="coerce",
    )

    hrmax75 = pd.to_numeric(
        obtener_valor(
            fila,
            columnas,
            "HRMAX75",
        ),
        errors="coerce",
    )

    if (
        pd.isna(hrmax50)
        or pd.isna(hrmax75)
    ):
        raise ValueError(
            "HRMAX50 y HRMAX75 deben "
            "contener valores numéricos."
        )

    numeros_sesion = sorted(
        {
            int(coincidencia.group(1))
            for columna
            in datos_rpe.columns
            if (
                coincidencia
                := re.fullmatch(
                    r"SESION(\d+)",
                    normalizar(columna),
                )
            )
        }
    )

    sesiones = []

    for numero in numeros_sesion:

        fecha = convertir_fecha(
            obtener_valor(
                fila,
                columnas,
                f"SESION{numero}",
            )
        )

        if fecha is None:
            continue

        sesiones.append(
            {
                "numero": numero,
                "fecha": fecha,

                "FUERZA": {
                    "rpe": obtener_valor(
                        fila,
                        columnas,
                        f"RPE_FUERZA_SESION{numero}",
                    ),
                    "inicio": convertir_a_segundos(
                        obtener_valor(
                            fila,
                            columnas,
                            f"TIEMPOini_FUERZA_SESION{numero}",
                        )
                    ),
                    "fin": convertir_a_segundos(
                        obtener_valor(
                            fila,
                            columnas,
                            f"TIEMPOFIN_FUERZA_SESION{numero}",
                        )
                    ),
                },

                "FUNCIONAL": {
                    "rpe": obtener_valor(
                        fila,
                        columnas,
                        f"RPE_FUNCIONAL_SESION{numero}",
                    ),
                    "inicio": convertir_a_segundos(
                        obtener_valor(
                            fila,
                            columnas,
                            f"TIEMPOini_FUNCIONAL_SESION{numero}",
                        )
                    ),
                    "fin": convertir_a_segundos(
                        obtener_valor(
                            fila,
                            columnas,
                            f"TIEMPOFIN_FUNCIONAL_SESION{numero}",
                        )
                    ),
                },

                "RESISTENCIA": {
                    "rpe": obtener_valor(
                        fila,
                        columnas,
                        f"RPE_RESIST_SESION{numero}",
                        f"RPE_RESISTENCIA_SESION{numero}",
                    ),
                    "inicio": convertir_a_segundos(
                        obtener_valor(
                            fila,
                            columnas,
                            f"TIEMPOini_RESIT_SESION{numero}",
                            f"TIEMPOini_RESIST_SESION{numero}",
                            f"TIEMPOini_RESISTENCIA_SESION{numero}",
                        )
                    ),
                    "fin": convertir_a_segundos(
                        obtener_valor(
                            fila,
                            columnas,
                            f"TIEMPOFIN_RESIST_SESION{numero}",
                            f"TIEMPOFIN_RESISTENCIA_SESION{numero}",
                        )
                    ),
                },
            }
        )

    if not sesiones:
        raise ValueError(
            "No se encontraron sesiones "
            "con fecha en la hoja RPE."
        )

    return {
        "hrmax50": float(hrmax50),
        "hrmax75": float(hrmax75),
        "sesiones": sesiones,
    }


# ================================================================
# CÁLCULO DE LAS ZONAS
# ================================================================

def calcular_zonas(
    datos,
    inicio,
    fin,
    hrmax,
    periodo,
    incluir_menores_60,
    recortar_intervalos,
    decimales_minutos,
):
    avisos = []

    if inicio is None or fin is None:
        return (
            None,
            ["Falta el tiempo inicial o final."],
        )

    if fin < inicio:
        return (
            None,
            [
                "El tiempo final es menor "
                "que el inicial."
            ],
        )

    inicio_usado = float(inicio)
    fin_usado = float(fin)

    minimo_registro = float(
        datos["tiempo_s"].min()
    )

    maximo_registro = float(
        datos["tiempo_s"].max()
    )

    if (
        inicio_usado < minimo_registro
        or fin_usado > maximo_registro
    ):

        if not recortar_intervalos:
            return (
                None,
                [
                    "El intervalo queda fuera "
                    "del registro de FC."
                ],
            )

        inicio_usado = max(
            inicio_usado,
            minimo_registro,
        )

        fin_usado = min(
            fin_usado,
            maximo_registro,
        )

        avisos.append(
            "Intervalo recortado al periodo "
            "disponible de FC."
        )

    if fin_usado < inicio_usado:
        return (
            None,
            avisos
            + [
                "El intervalo no se solapa "
                "con el registro de FC."
            ],
        )

    frecuencias = datos.loc[
        (
            datos["tiempo_s"]
            >= inicio_usado - 1e-6
        )
        & (
            datos["tiempo_s"]
            <= fin_usado + 1e-6
        ),
        "hr",
    ].to_numpy(
        dtype=float
    )

    if len(frecuencias) == 0:
        return (
            None,
            avisos
            + [
                "No hay muestras de FC "
                "en el intervalo."
            ],
        )

    umbrales = {
        porcentaje: redondear_umbral(
            hrmax
            * porcentaje
            / 100
        )
        for porcentaje in [
            60,
            70,
            80,
            90,
            100,
            110,
        ]
    }

    if incluir_menores_60:

        mascara_z1 = (
            frecuencias
            <= umbrales[70]
        )

        segundos_bajo_60 = 0

    else:

        mascara_z1 = (
            (
                frecuencias
                >= umbrales[60]
            )
            & (
                frecuencias
                <= umbrales[70]
            )
        )

        segundos_bajo_60 = (
            float(
                np.sum(
                    frecuencias
                    < umbrales[60]
                )
            )
            * periodo
        )

    mascaras = [
        mascara_z1,

        (
            (
                frecuencias
                >= umbrales[70]
            )
            & (
                frecuencias
                < umbrales[80]
            )
        ),

        (
            (
                frecuencias
                >= umbrales[80]
            )
            & (
                frecuencias
                < umbrales[90]
            )
        ),

        (
            (
                frecuencias
                >= umbrales[90]
            )
            & (
                frecuencias
                < umbrales[100]
            )
        ),

        (
            (
                frecuencias
                >= umbrales[100]
            )
            & (
                frecuencias
                < umbrales[110]
            )
        ),

        frecuencias >= umbrales[110],
    ]

    segundos = [
        float(
            np.sum(mascara)
        )
        * periodo
        for mascara in mascaras
    ]

    segundos_limpios = [
        (
            int(round(valor))
            if (
                abs(
                    valor
                    - round(valor)
                )
                < 1e-8
            )
            else round(valor, 3)
        )
        for valor in segundos
    ]

    minutos = [
        round(
            valor / 60,
            decimales_minutos,
        )
        for valor in segundos
    ]

    return (
        {
            "umbrales": umbrales,
            "segundos": segundos_limpios,
            "minutos": minutos,
            "inicio_usado": inicio_usado,
            "fin_usado": fin_usado,
            "muestras": len(frecuencias),
            "bajo60": segundos_bajo_60,
        },
        avisos,
    )


# ================================================================
# EMPAREJAMIENTO DE SESIONES
# ================================================================

def emparejar_sesion(
    sesion_rpe,
    sesiones_hrv,
    hojas_usadas,
    modo,
    permitir_fallback,
):
    disponibles = [
        sesion
        for sesion in sesiones_hrv
        if sesion["hoja"] not in hojas_usadas
    ]

    if modo in {
        "Fecha exacta",
        "Automático",
    }:

        candidatos = [
            sesion
            for sesion in disponibles
            if (
                sesion["fecha"]
                == sesion_rpe["fecha"]
            )
        ]

        if len(candidatos) == 1:
            return (
                candidatos[0],
                "fecha",
                "",
            )

        if (
            modo == "Fecha exacta"
            or not permitir_fallback
        ):
            return (
                None,
                "fecha",
                "No existe una hoja HRV "
                "con la misma fecha.",
            )

    if modo in {
        "Orden de las hojas",
        "Automático",
    }:

        if disponibles:

            sesion_hrv = disponibles[0]
            aviso = ""

            if (
                sesion_hrv["fecha"]
                != sesion_rpe["fecha"]
            ):
                aviso = (
                    "Emparejada por orden pese "
                    "a fechas distintas: "
                    f"RPE {sesion_rpe['fecha']} / "
                    f"HRV {sesion_hrv['fecha']}."
                )

            return (
                sesion_hrv,
                "orden",
                aviso,
            )

    return (
        None,
        modo,
        "No se pudo emparejar la sesión.",
    )


# ================================================================
# FORMATO DEL EXCEL
# ================================================================

def formatear_excel(ruta):
    libro = load_workbook(ruta)

    azul = "1F4E78"
    verde = "548235"
    azul_claro = "D9EAF7"
    blanco = "FFFFFF"
    rojo_claro = "FCE4D6"

    borde = Border(
        left=Side(
            style="thin",
            color="A6A6A6",
        ),
        right=Side(
            style="thin",
            color="A6A6A6",
        ),
        top=Side(
            style="thin",
            color="A6A6A6",
        ),
        bottom=Side(
            style="thin",
            color="A6A6A6",
        ),
    )

    for hoja in libro.worksheets:

        hoja.sheet_view.showGridLines = False

        if hoja.title == "CONTROL":
            hoja.freeze_panes = "A2"
        else:
            hoja.freeze_panes = "A3"

        for fila in hoja.iter_rows():

            for celda in fila:

                celda.border = borde

                celda.alignment = Alignment(
                    horizontal="center",
                    vertical="center",
                    wrap_text=True,
                )

        for celda in hoja[1]:

            celda.font = Font(
                bold=True,
                color=blanco,
            )

            celda.fill = PatternFill(
                "solid",
                fgColor=azul,
            )

        if hoja.title != "CONTROL":

            for numero_fila in range(
                1,
                hoja.max_row + 1,
            ):

                valor = hoja.cell(
                    numero_fila,
                    1,
                ).value

                if (
                    isinstance(valor, str)
                    and valor.startswith(
                        "PARTE DE"
                    )
                ):

                    hoja.merge_cells(
                        start_row=numero_fila,
                        start_column=1,
                        end_row=numero_fila,
                        end_column=9,
                    )

                    hoja.cell(
                        numero_fila,
                        1,
                    ).font = Font(
                        bold=True,
                        color=blanco,
                    )

                    hoja.cell(
                        numero_fila,
                        1,
                    ).fill = PatternFill(
                        "solid",
                        fgColor=verde,
                    )

                    for columna in range(
                        1,
                        10,
                    ):

                        hoja.cell(
                            numero_fila + 1,
                            columna,
                        ).font = Font(
                            bold=True
                        )

                        hoja.cell(
                            numero_fila + 1,
                            columna,
                        ).fill = PatternFill(
                            "solid",
                            fgColor=azul_claro,
                        )

        else:

            columna_avisos = None

            for celda in hoja[1]:

                if celda.value == "Avisos":
                    columna_avisos = celda.column
                    break

            if columna_avisos:

                for numero_fila in range(
                    2,
                    hoja.max_row + 1,
                ):

                    if hoja.cell(
                        numero_fila,
                        columna_avisos,
                    ).value:

                        for columna in range(
                            1,
                            hoja.max_column + 1,
                        ):

                            hoja.cell(
                                numero_fila,
                                columna,
                            ).fill = PatternFill(
                                "solid",
                                fgColor=rojo_claro,
                            )

        for numero_columna in range(
            1,
            hoja.max_column + 1,
        ):

            longitudes = [
                (
                    len(
                        str(
                            hoja.cell(
                                numero_fila,
                                numero_columna,
                            ).value
                        )
                    )
                    if (
                        hoja.cell(
                            numero_fila,
                            numero_columna,
                        ).value
                        is not None
                    )
                    else 0
                )
                for numero_fila in range(
                    1,
                    hoja.max_row + 1,
                )
            ]

            anchura = min(
                max(
                    longitudes + [10]
                )
                + 2,
                40,
            )

            hoja.column_dimensions[
                get_column_letter(
                    numero_columna
                )
            ].width = anchura

    libro.save(ruta)


# ================================================================
# GENERACIÓN DEL EXCEL
# ================================================================

def generar_excel(
    archivo_hrv,
    archivo_rpe,
    sujeto,
    hoja_rpe,
    incluir_menores_60,
    recortar_intervalos,
    decimales_minutos,
    modo_emparejamiento,
    permitir_fallback,
    nombre_salida,
):
    informacion_rpe = leer_valoracion_rpe(
        ruta=archivo_rpe,
        hoja_rpe=hoja_rpe,
        sujeto=sujeto,
    )

    libro_hrv = pd.ExcelFile(
        archivo_hrv
    )

    sesiones_hrv = [
        leer_hoja_hrv(
            ruta=archivo_hrv,
            hoja=nombre_hoja,
        )
        for nombre_hoja
        in libro_hrv.sheet_names
    ]

    zonas = [
        "Z1",
        "Z2",
        "Z3",
        "Z4",
        "Z5",
        "Z6",
    ]

    rangos = [
        "60–70%",
        "70–80%",
        "80–90%",
        "90–100%",
        "100–110%",
        ">110%",
    ]

    control = []
    hojas_usadas = set()
    nombres_generados = set()

    if not nombre_salida.lower().endswith(
        ".xlsx"
    ):
        nombre_salida += ".xlsx"

    with pd.ExcelWriter(
        nombre_salida,
        engine="openpyxl",
    ) as escritor:

        sesiones_ordenadas = sorted(
            informacion_rpe["sesiones"],
            key=lambda elemento: elemento["numero"],
        )

        for sesion_rpe in sesiones_ordenadas:

            (
                sesion_hrv,
                metodo,
                aviso_emparejamiento,
            ) = emparejar_sesion(
                sesion_rpe=sesion_rpe,
                sesiones_hrv=sesiones_hrv,
                hojas_usadas=hojas_usadas,
                modo=modo_emparejamiento,
                permitir_fallback=permitir_fallback,
            )

            if sesion_hrv is None:

                control.append(
                    {
                        "Sesión": sesion_rpe["numero"],
                        "Fecha RPE": sesion_rpe["fecha"],
                        "Hoja HRV": "",
                        "Fecha HRV": "",
                        "Método": metodo,
                        "Parte": "",
                        "Inicio solicitado": "",
                        "Fin solicitado": "",
                        "Inicio usado": "",
                        "Fin usado": "",
                        "Muestras": "",
                        "Segundos Z1–Z6": "",
                        "Segundos <60%": "",
                        "Avisos": aviso_emparejamiento,
                    }
                )

                continue

            hojas_usadas.add(
                sesion_hrv["hoja"]
            )

            nombre_hoja = nombre_hoja_seguro(
                nombre=(
                    f"S{sesion_rpe['numero']}_"
                    f"{sesion_hrv['hoja']}"
                ),
                existentes=nombres_generados,
            )

            nombres_generados.add(
                nombre_hoja
            )

            fila_inicio = 0

            for parte in [
                "FUERZA",
                "FUNCIONAL",
                "RESISTENCIA",
            ]:

                informacion_parte = (
                    sesion_rpe[parte]
                )

                resultado_50, avisos_50 = calcular_zonas(
                    datos=sesion_hrv["datos"],
                    inicio=informacion_parte["inicio"],
                    fin=informacion_parte["fin"],
                    hrmax=informacion_rpe["hrmax50"],
                    periodo=sesion_hrv["periodo"],
                    incluir_menores_60=incluir_menores_60,
                    recortar_intervalos=recortar_intervalos,
                    decimales_minutos=decimales_minutos,
                )

                resultado_75, avisos_75 = calcular_zonas(
                    datos=sesion_hrv["datos"],
                    inicio=informacion_parte["inicio"],
                    fin=informacion_parte["fin"],
                    hrmax=informacion_rpe["hrmax75"],
                    periodo=sesion_hrv["periodo"],
                    incluir_menores_60=incluir_menores_60,
                    recortar_intervalos=recortar_intervalos,
                    decimales_minutos=decimales_minutos,
                )

                avisos = list(
                    dict.fromkeys(
                        [
                            aviso
                            for aviso in (
                                [aviso_emparejamiento]
                                + avisos_50
                                + avisos_75
                            )
                            if aviso
                        ]
                    )
                )

                if (
                    resultado_50 is None
                    or resultado_75 is None
                ):

                    tabla = pd.DataFrame(
                        {
                            "Aviso": [
                                " | ".join(
                                    avisos
                                )
                            ]
                        }
                    )

                else:

                    limites_50 = [
                        resultado_50["umbrales"][70],
                        resultado_50["umbrales"][80],
                        resultado_50["umbrales"][90],
                        resultado_50["umbrales"][100],
                        resultado_50["umbrales"][110],
                        resultado_50["umbrales"][110],
                    ]

                    limites_75 = [
                        resultado_75["umbrales"][70],
                        resultado_75["umbrales"][80],
                        resultado_75["umbrales"][90],
                        resultado_75["umbrales"][100],
                        resultado_75["umbrales"][110],
                        resultado_75["umbrales"][110],
                    ]

                    tabla = pd.DataFrame(
                        {
                            "Zona": zonas,
                            "%": rangos,

                            "HR 0.5": limites_50,
                            "segundos 0.5": resultado_50["segundos"],
                            "minutos 0.5": resultado_50["minutos"],

                            "HR 0.75": limites_75,
                            "segundos 0.75": resultado_75["segundos"],
                            "minutos 0.75": resultado_75["minutos"],

                            f"RPE {parte}": [
                                informacion_parte["rpe"],
                                "",
                                "",
                                "",
                                "",
                                "",
                            ],
                        }
                    )

                    control.append(
                        {
                            "Sesión": sesion_rpe["numero"],
                            "Fecha RPE": sesion_rpe["fecha"],
                            "Hoja HRV": sesion_hrv["hoja"],
                            "Fecha HRV": sesion_hrv["fecha"],
                            "Método": metodo,
                            "Parte": parte,

                            "Inicio solicitado": segundos_a_hms(
                                informacion_parte["inicio"]
                            ),

                            "Fin solicitado": segundos_a_hms(
                                informacion_parte["fin"]
                            ),

                            "Inicio usado": segundos_a_hms(
                                resultado_50["inicio_usado"]
                            ),

                            "Fin usado": segundos_a_hms(
                                resultado_50["fin_usado"]
                            ),

                            "Muestras": resultado_50["muestras"],

                            "Segundos Z1–Z6": sum(
                                resultado_50["segundos"]
                            ),

                            "Segundos <60%": resultado_50["bajo60"],

                            "Avisos": " | ".join(
                                avisos
                            ),
                        }
                    )

                pd.DataFrame(
                    [
                        [
                            f"PARTE DE {parte}"
                        ]
                    ]
                ).to_excel(
                    escritor,
                    sheet_name=nombre_hoja,
                    startrow=fila_inicio,
                    index=False,
                    header=False,
                )

                tabla.to_excel(
                    escritor,
                    sheet_name=nombre_hoja,
                    startrow=fila_inicio + 1,
                    index=False,
                )

                fila_inicio += (
                    len(tabla)
                    + 4
                )

        pd.DataFrame(
            control
        ).to_excel(
            escritor,
            sheet_name="CONTROL",
            index=False,
        )

    formatear_excel(
        nombre_salida
    )

    return (
        nombre_salida,
        control,
    )


# ================================================================
# IDENTIFICACIÓN AUTOMÁTICA DE LOS ARCHIVOS
# ================================================================

def identificar_archivos(
    archivos,
    hoja_rpe,
):
    candidatos_rpe = []
    candidatos_hrv = []

    for archivo in archivos:

        libro = load_workbook(
            archivo,
            read_only=True,
            data_only=True,
        )

        nombres_hojas = libro.sheetnames
        libro.close()

        if hoja_rpe in nombres_hojas:
            candidatos_rpe.append(
                archivo
            )
        else:
            candidatos_hrv.append(
                archivo
            )

    if len(candidatos_rpe) != 1:
        raise ValueError(
            "Debe existir exactamente un Excel "
            f"con una hoja llamada «{hoja_rpe}». "
            f"Encontrados: {candidatos_rpe}"
        )

    if len(candidatos_hrv) != 1:
        raise ValueError(
            "Debe existir exactamente un Excel "
            "de sesiones HRV. "
            f"Encontrados: {candidatos_hrv}"
        )

    return (
        candidatos_hrv[0],
        candidatos_rpe[0],
    )


# ================================================================
# PANEL INTERACTIVO
# ================================================================

ARCHIVOS_SUBIDOS = []

titulo = widgets.HTML(
    """
    <h3 style="margin-bottom:4px;">
        Cálculo de zonas de frecuencia cardiaca
    </h3>
    <p style="margin-top:0;">
        Configura el análisis sin modificar el código.
    </p>
    """
)

sujeto_widget = widgets.Text(
    value="S020",
    description="Sujeto:",
    layout=widgets.Layout(
        width="320px"
    ),
)

hoja_rpe_widget = widgets.Text(
    value="BD",
    description="Hoja RPE:",
    layout=widgets.Layout(
        width="320px"
    ),
)

incluir_menores_60_widget = widgets.Checkbox(
    value=False,
    description=(
        "Incluir la FC <60% dentro de Z1"
    ),
    indent=False,
)

recortar_intervalos_widget = widgets.Checkbox(
    value=True,
    description=(
        "Recortar intervalos al registro disponible"
    ),
    indent=False,
)

decimales_widget = widgets.BoundedIntText(
    value=3,
    min=0,
    max=8,
    step=1,
    description="Decimales:",
    layout=widgets.Layout(
        width="230px"
    ),
)

modo_emparejamiento_widget = widgets.Dropdown(
    options=[
        "Automático",
        "Fecha exacta",
        "Orden de las hojas",
    ],
    value="Automático",
    description="Emparejar:",
    layout=widgets.Layout(
        width="360px"
    ),
)

fallback_widget = widgets.Checkbox(
    value=False,
    description=(
        "Permitir emparejamiento por orden "
        "si la fecha no coincide"
    ),
    indent=False,
)

nombre_salida_widget = widgets.Text(
    value="S020_zonas_FC_por_sesion.xlsx",
    description="Salida:",
    layout=widgets.Layout(
        width="500px"
    ),
)

boton_seleccionar = widgets.Button(
    description="1. Seleccionar Excel",
    button_style="info",
    icon="upload",
    layout=widgets.Layout(
        width="220px"
    ),
)

boton_ejecutar = widgets.Button(
    description="2. Ejecutar análisis",
    button_style="success",
    icon="play",
    layout=widgets.Layout(
        width="220px"
    ),
)

estado_archivos = widgets.HTML(
    """
    <b>Archivos:</b>
    todavía no se han seleccionado.
    """
)

panel_resultados = widgets.Output()


# ================================================================
# FUNCIONES DE LOS BOTONES
# ================================================================

def actualizar_nombre_salida(cambio):
    sujeto = (
        cambio["new"].strip()
        or "resultado"
    )

    nombre_salida_widget.value = (
        f"{sujeto}_zonas_FC_por_sesion.xlsx"
    )


sujeto_widget.observe(
    actualizar_nombre_salida,
    names="value",
)


def seleccionar_archivos(_):
    global ARCHIVOS_SUBIDOS

    with panel_resultados:

        clear_output()

        print(
            "Selecciona conjuntamente:"
        )

        print(
            "1. El Excel de sesiones HRV."
        )

        print(
            "2. El Excel VALORACION RPE."
        )

    archivos_cargados = files.upload()

    ARCHIVOS_SUBIDOS = [
        nombre
        for nombre
        in archivos_cargados
        if nombre.lower().endswith(
            ".xlsx"
        )
    ]

    if len(ARCHIVOS_SUBIDOS) < 2:

        estado_archivos.value = """
        <b style="color:#b00020;">
            Debes seleccionar al menos
            dos archivos .xlsx.
        </b>
        """

        return

    lista_archivos = "<br>".join(
        f"• {nombre}"
        for nombre
        in ARCHIVOS_SUBIDOS
    )

    estado_archivos.value = (
        "<b>Archivos seleccionados:</b><br>"
        + lista_archivos
    )

    with panel_resultados:

        clear_output()

        print(
            "Archivos cargados correctamente."
        )


def ejecutar_analisis(_):
    boton_ejecutar.disabled = True

    with panel_resultados:

        clear_output()

        try:

            if len(ARCHIVOS_SUBIDOS) < 2:
                raise ValueError(
                    "Primero pulsa «Seleccionar Excel» "
                    "y carga los dos archivos."
                )

            (
                archivo_hrv,
                archivo_rpe,
            ) = identificar_archivos(
                archivos=ARCHIVOS_SUBIDOS,
                hoja_rpe=hoja_rpe_widget.value.strip(),
            )

            print(
                f"Archivo HRV: {archivo_hrv}"
            )

            print(
                f"Archivo RPE: {archivo_rpe}"
            )

            print(
                f"Sujeto: "
                f"{sujeto_widget.value.strip()}"
            )

            print(
                "Procesando sesiones..."
            )

            (
                ruta_salida,
                tabla_control,
            ) = generar_excel(
                archivo_hrv=archivo_hrv,
                archivo_rpe=archivo_rpe,
                sujeto=sujeto_widget.value.strip(),
                hoja_rpe=hoja_rpe_widget.value.strip(),
                incluir_menores_60=(
                    incluir_menores_60_widget.value
                ),
                recortar_intervalos=(
                    recortar_intervalos_widget.value
                ),
                decimales_minutos=(
                    decimales_widget.value
                ),
                modo_emparejamiento=(
                    modo_emparejamiento_widget.value
                ),
                permitir_fallback=(
                    fallback_widget.value
                ),
                nombre_salida=(
                    nombre_salida_widget.value.strip()
                ),
            )

            print()
            print(
                "Análisis completado correctamente."
            )

            print(
                f"Excel generado: {ruta_salida}"
            )

            print(
                f"Filas de control: "
                f"{len(tabla_control)}"
            )

            print(
                "La descarga comenzará automáticamente."
            )

            files.download(
                ruta_salida
            )

        except Exception as error:

            print()
            print("ERROR:")
            print(str(error))

        finally:

            boton_ejecutar.disabled = False


boton_seleccionar.on_click(
    seleccionar_archivos
)

boton_ejecutar.on_click(
    ejecutar_analisis
)


# ================================================================
# PRESENTACIÓN DEL PANEL
# ================================================================

panel = widgets.VBox(
    [
        titulo,

        widgets.HTML(
            "<b>Identificación</b>"
        ),

        widgets.HBox(
            [
                sujeto_widget,
                hoja_rpe_widget,
            ]
        ),

        widgets.HTML(
            "<b>Criterios de cálculo</b>"
        ),

        incluir_menores_60_widget,
        recortar_intervalos_widget,

        widgets.HBox(
            [
                decimales_widget,
                modo_emparejamiento_widget,
            ]
        ),

        fallback_widget,
        nombre_salida_widget,

        widgets.HBox(
            [
                boton_seleccionar,
                boton_ejecutar,
            ]
        ),

        estado_archivos,
        panel_resultados,
    ]
)

display(panel)

"""#Licencia

![68747470733a2f2f692e6372656174697665636f6d6d6f6e732e6f72672f6c2f62792f342e302f38387833312e706e67.png](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFgAAAAfCAMAAABUFvrSAAAAAXNSR0IB2cksfwAAAARnQU1BAACxjnz7UZMAAAAgY0hSTQAAeiUAAICDAAD5/wAAgOkAAHUwAADqYAAAOpgAABdvkl/FRgAAAW5QTFRFAAAAAAAA////////////7+/v39/f1tXV09bS0tXS0tXR0dTR0dTQ0NTQ0NPPz9PPztLOztHNzdHNzdHMz8/PzdDMzNDMzNDLzM/Ly8/Ly8/Ky87Kys3Jyc3Jyc3IyMzIyMzHx8vHxsrGxsrFxcnFxcnExMnExMjDw8jDxMfDw8fCwsfCwcXAwMXAwMW/wMS/v8S+v8O+vsO+vsK9vcK9vcK8v7+/vMG8vMG7vMC8u8C7u8C6ur+6ur+5ub65ub64uL23t7y2tru1tbq0tLqztLmzs7iysrixsrexsbewsbawsLavsLWvr7Wur7SusLOvrrStrrOtr7KvrbOsrLKrr6+vq7Gqn6OenqCdn5+flpmWk5iTkZSRkZORj4+PiYyJhIaEhIWEgoWCgICAfX98fH98eXx5cHJvcHBwYGBgXV5dUFFQUFBQQ0RDQEBAPj8+NTY1MjMxMDAwKSkpKCkoICAgGxsbEBAQDg4ODQ4N2y3MbAAAAAR0Uk5T/wAKDnDBpeYAAALVSURBVHjatZX9V9JgFMdvNQh1Tme2zU1othSl5WsQZoqIrxmmqaUpqS2JKczibfLfd5+hHCYybB6/B859ftg+5+57Xx54Ag+iR/hPxGPRSXVYkf2SwHGC2C8rQXUiOhdPLK992tze3vn6/wKLOxseCykBkWXoNp+vrYNh+wJKaDQ8S8jJze0dl2TkvgkOSCx9kqsAqpI7prtFeUh9i+SV9eRWY8rpAqAKaWdwDLkyz6TKUFP5kOECg2p4Lr60ut6Q8kERwMhkDIDigRM4OhaUOfocT6auRSKabuLxfORZYGg0GltAM26k/O0Ssl4K5c3C5YEDeDI0wBOuqXmoqvYRXRzh5NDEzHwCU7aDi6DjMwDkQSg6gFVFYpCb91I1efKYMyMqahhT/rhh8yIN2adVMCoL6ebg4RdsCrmYrp182B0Ijs/EF1eTW/XgAtRl4IVCc7Ai0mUweymbPCaU6T5FfRdLrNi9AINC6QA6iQY0B8s9JwCanUvsg2NWDk3Nohd2cIZCAYrEjAPY35UDE42IZA1Dq4Yf+IoJOaafeLG0tuEOLNEV0BEIRMauFXTysZUOcXD0/fziWtKdFUI7AKaYh5I3UtrPY3vslvYtL9oERY1iwyG4oXgALYvH+wAiFGX5XAvWF/i4l41gbDfKod3cgu0DksEBuYsVnt6ShlaQ0GCF00g7F++qaleBZFOhpcbiEXIRIK9n8q2WkL/rHEyq1m67hhWoErabPzj+odpubtam3JNCL24fkNdTcwvLZPLcLPpX1kh7HUbaJRiX0N5tSyjFBoYncPDIEnIFhlOJOUNy3RryWmtT+gn31G+hs37RezQT4A/Nn8K99YvrPLtxNdHPv0MzVeeDHFqTBWav/jJNMXxzLlBXP+oubkgsnbq+/g9pVnLy4Xptwl3094vY00W3+3ztNMP2fb4AB9mMaK2Lo2lJ4HlBmj4iWLcZP7wePwz20T8rQcP0CuFIbQAAAABJRU5ErkJggg==)

Este obra está bajo una licencia de [Creative Commons Reconocimiento 4.0 Internacional.](https://creativecommons.org/licenses/by/4.0/)

#Autor

Aarón Miralles Iborra (aaron.mirallesi@umh.es)
"""